project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Contenido
      - about.qmd
      - section1.qmd
      - section2.qmd
      - section3.qmd
    contents: 
      - href: talleres.qmd
        text: Talleres
      - taller1.qmd
      - taller2.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



