---
title: Matrices
format: html
filters:
  - pyodide
---


Supongamos que tenemos una ciudad solo con 4 casas, podemos colocar una nomenclatura para cada una de la casa usando solo números de la siguiente forma:

```{python}
#| echo: false
import matplotlib.pyplot as plt

# Coordenadas de las casas
houses = {
    "1": (1, 3),
    "2": (3, 3),
    "3": (1, 1),
    "4": (3, 1)
}

fig, ax = plt.subplots()

# Dibujar cada casa y agregar su nombre
for num, (x, y) in houses.items():
    ax.plot(x, y, 'o', markersize=10)
    ax.text(x + 0.1, y + 0.1, f'Casa {num}', fontsize=12)

# En el punto (1.5,2.5) escribe (1,1)
ax.text(1.5, 2.5, '(1,1)', fontsize=12)
ax.text(2.5, 2.5, '(1,2)', fontsize=12)
ax.text(1.5, 1.5, '(2,1)', fontsize=12)
ax.text(2.5, 1.5, '(2,2)', fontsize=12)

ax.set_title('')
ax.axis('off')

ax.axhline(y=2, color='red', linestyle='--')
ax.axvline(x=2, color='red', linestyle='--')
ax.legend()
plt.show()
```


Note que en la casa 1 la dirección sería (1,1), en la casa 2 la dirección sería (1,2), en la casa 3 la dirección sería (2,1) y en la casa 4 la dirección sería (2,2). De esta forma podemos decir encontrar que esta "viviendo" en cada casa. Podemos suponer que en la casa 1 vive el  número 1, en la casa 2 el número 2 y así sucesivamente. Para representar esto podemos usar una notación matricial de la siguiente forma:

$$
A=\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
$$

De esta forma podemos definir que en la dirección $(1,1)$
esta viviendo el número 1, esto lo podemos representar de la forma

$$A(1,1)=1,$$

similarmente 

$$A(1,2)=2, \ A(2,1)=3 \text{ y } A(2,2)=4$$

El elememto $A$ se llama una matriz, cuya dimensión es $2\times 2$ que representan las casas de la ciudad. Llamaremos filas de la matriz $A$ a los elementos que están en la misma fila y columnas a los elementos que están en la misma columna. Por ejemplo la fila 1 de la matriz $A$ es $(1,2)$ y la columna 1 de la matriz $A$ es $\begin{bmatrix}1\\3\end{bmatrix}$.


# Operaciones con matrices

## Suma de matrices

## Multiplicación por escalar 


## Multiplicación de matrices

## Transpuesta de una matriz

## Matriz identidad 

## Inversa de una matriz
